### ISSUE TITLE
Better deps handling

### ISSUE THREAD

**Issue by vicb** [redstone-dart/redstone#19]
The pubspec.yaml reads as follow

```
  di: ">=0.0.40 <2.0.0"
  stack_trace: ">=0.9.1 <2.0.0"
```

You can introduce a BC break by running a `pub update` because `di` and `stack_trace` can have a BC break. According to semver, the constraints should be:

- `>=0.m.p <0.m+1.0' for pre 1.0 pkgs,
- '>=M.m.p <M+1.0.0` for post 1.0

**Comment by Pacane** [comment]
Not a problem anymore.
