### ISSUE TITLE
Better stack trace for debugging

### ISSUE THREAD

**Issue by cgarciae** [redstone-dart/redstone#86]
Any chance you can include [stack_trace] (https://pub.dartlang.org/packages/stack_trace) when running the server?

**Comment by cgarciae** [comment]
Especially useful `Chain.capture`

**Comment by luizmineo** [comment]
Thanks for reporting. This is already implemented in [v0.6.0-beta.1](https://github.com/luizmineo/redstone.dart/tree/v0.6)
