### ISSUE TITLE
Enable routing to shelf_handlers

### ISSUE THREAD

**Issue by wstrange** [redstone-dart/redstone#90]
Perhaps this just a documentation thing, but it is not obvious how to route to a shelf handler.

How do I arrange for a *specific* route to be handled by a shelf handler instead of a "redstone" handler?   

Let's say I have a shelf oauth2 callback handler.  I want  "/oauth2/callback" to be handled by the shelf handler.  The current mechanism seems to route to shelf only when all other handlers have been tried.  If I have a bunch of shelf handlers, it is not clear to me how I integrate them with the routing mechanism.

**Comment by luizmineo** [comment]
Currently, there is no way to directly bind a shelf handler with a path, but you can wrap a shelf handler. Example:

```dart
@Route('/mypath')
myService() {
   return myShelfHandler(request.shelfRequest);
}
```

Let me know if that helps.
