### ISSUE TITLE
A matcher for all routes with a path parameter

### ISSUE THREAD

**Issue by danschultz** [redstone-dart/redstone#92]
I'm trying to define a route that matches everything, but also passes the path as a param to its annotated function. For example:

* /: `path = ""`
* /foo: `path = "foo"`
* /foo/bar: `path = "foo/bar"`

I tried the following, and it works for sub-paths, but fails on root `/`.

```dart
@app.Route("/:path*", responseType: "text/html", matchSubPaths: true)
String all(String path) => "Hello World";
```

Is this possible with Redstone?

**Comment by cgarciae** [comment]
What are you trying to accomplish? An Interceptor or route decorator plugin might what you need.

**Comment by danschultz** [comment]
I'm trying to write an isomorphic Dart app using React. I'd like Redstone to respond to any path, and pass the path into a React component which will handle the routing.

**Comment by cgarciae** [comment]
How about
```dart
@app.Route ('*', matchSubPaths: true)
anyPath () => app.request.url;
```

**Comment by danschultz** [comment]
That works, but I also need access to the path in order to pass it into my server-side React component which is handling the routing. I tried the following, but I get a 404:

```dart
@app.Route (':path*', matchSubPaths: true)
anyPath(String path) => app.request.url;
```

**Comment by cgarciae** [comment]
Is this enough?

``` dart
@app.Route ('*', matchSubPaths: true)
anyPath()
{
    var path = app.request.url;
    //Do something with path
}
```

The `url` IS the path.

**Comment by luizmineo** [comment]
The following example works fine in [v0.6.0-beta.1](https://github.com/luizmineo/redstone.dart/tree/v0.6)

```dart
import 'redstone/redstone.dart';

@Route(":path*", responseType: "text/html")
String all(String path) => path;
```

**Comment by danschultz** [comment]
Sorry @cgarciae, I overlooked `app.request.url`. I'll give that and v0.6.0 beta a try.
