### ISSUE TITLE
WARNING: dart:mirrors support in dart2js is experimental, * and not recommended.

### ISSUE THREAD

**Issue by SatWiz** [redstone-dart/redstone#96]
When convert to JS I having this warning for my project using package:redstone_mapper:

* WARNING: dart:mirrors support in dart2js is experimental,
*          and not recommended.
*          This implementation of mirrors is incomplete,
*          and often greatly increases the size of the generated
*          JavaScript code.

My question, is it save to use redstone_mapper in production?

**Comment by austincummings** [comment]
You can get rid of this by adding `redstone_mapper` to the [transformers](https://www.dartlang.org/tools/pub/assets-and-transformers.html) section in your pubspec.yaml file.

**Comment by SatWiz** [comment]
I saw that in the older docs. But it looks like it is not working in version 0.2.0-beta.1 which I used now. As I still get the warning with the redstone_mapper in the yaml_file.

**Comment by SatWiz** [comment]
Are you still working on the 0.2.0 transformer and is it better to use previous version of the redstone_mapper for more stability?

**Comment by austincummings** [comment]
@SatWiz I would recommend using the previous version. This project is currently going through a ownership transition and we still need to learn the code.

**Comment by Pacane** [comment]
@SatWiz It seems like the transformer isn't working correctly. I personally stopped using redstone_mapper in favor of dogma_codegen. However, if you are still having problems with this, I could take a look at it.

**Comment by SatWiz** [comment]
thanks Pacane, thought I had use dart bridge as replacement. So no need anymore ;)

**Comment by Pacane** [comment]
If you want some help about using dogma-codegen though. let me know. I've also written a small post about it. http://stacktrace.ca/json-serialization-in-dart-with-dogma

**Comment by ghost** [comment]
Hello, 

I am getting this error while I am deploying this.

Building security_monkey... (22.4s)
[Info from Dart2JS]:
Compiling security_monkey|web/main.dart...
[Dart2JS]:
web/main.dart:

---
- WARNING: dart:mirrors support in dart2js is experimental,
-          and not recommended.
-          This implementation of mirrors is incomplete,
-          and often greatly increases the size of the generated
-          JavaScript code.
  *
- Your app imports dart:mirrors via:
-   main.dart => package:security_monkey => dart:mirrors
-   main_generated_type_factory_maps.dart => package:security_monkey => dart:mirrors
-   main_static_metadata.dart => package:security_monkey => dart:mirrors
-   main_static_type_to_uri_mapper.dart => package:security_monkey => dart:mirrors
  *
- You can disable this message by using the --enable-experimental-mirrors
- command-line flag.
  *
- To learn what to do next, please visit:
-    http://dartlang.org/dart2js-reflection
  ****************************************************************

**Comment by Pacane** [comment]
Show me your pubspec.

**Comment by ghost** [comment]
name: security_monkey
description: An AWS Policy Monitoring and Alerting Tool
version: 0.5.0
dependencies:
  angular: ">=1.1.0 <2.0.0"
  angular_ui: ">=0.6.8 <0.7.0"
  hammock: ">=0.4.0 <0.5.0"
  ng_infinite_scroll: ">=0.2.0 <0.3.0"
  web_components: ">=0.10.1 <0.11.0"
  browser: ">=0.10.0+2 <0.11.0"
  http_server: ">=0.9.5+1 <0.10.0"
  code_transformers: ">=0.2.5 <0.3.0"
  dart_to_js_script_rewriter: ">=0.0.2 <0.1.0"
  aws_policy_expander_minimizer: ">=0.0.5 <0.1.0"
dev_dependencies:
  unittest: '0.11.0+2'
redstone_mapper:
- angular
- dart_to_js_script_rewriter
- $dart2js:
  csp: true
  checked: false
  minify: true
  verbose: true
  suppressWarnings: false
  suppressHints: false
  terse: false
  author: yes
  homepage: https://github.com/Netflix/security_monkey

**Comment by Pacane** [comment]
wait, so are you serving an angular app from redstone?
