### ISSUE TITLE
Lets keep Redstone alive

### ISSUE THREAD

**Issue by cgarciae** [redstone-dart/redstone#98]
@luizmineo, @alexpaluzzi, @austincummings, @bruci, @financeCoding, @garywu125, @IOT-DSA, @jriggins, @kaendfinger, @kristianmandrup, @lukasz-madon, @platelk, @RedRoserade, @RobertMcDermot, @ronlobo, @sdeleuze, @vicb, @willmitchell, @SatWiz, @danschultz, @wstrange, @skoky, @digitalfiz, @nistvan86, @Emasoft, @seaneagan, @Pacane, @sonoranDesert, @OzzieOrca, @Kleak, @prujohn, @avastou, @hyousef, @digizen, @akofoed, @kevmoo, @petermetz, @y12studio 

First of all, sorry for the inconvenience of tagging you without knowing you. As you may or may not have read, **Luiz isn't going to be able to maintain Redstone anymore!** If we are here, I am sure we owe him our thanks for this great piece of software.

Open source is about collaboration, and I think we can "collaborate ourselves" out of this one. By that I mean: lets somehow organize to maintain Redstone. For myself, I depend on it, I've been looking at all the options and none completely satisfy me as the current Redstone.

I propose this:
1. Lets discuss what to do next
2. Create a "Start Developing" section on the wiki by those who maybe understand Redstone (hopefully @luizmineo can help us here because frankly I don't understand the internals of Redstone)
3. Create a roadmap based on `v0.6`

Thanks again to Luiz for all his hard work, and hope to hear from those interested.

**Comment by kaendfinger** [comment]
I'll offer to have it move to my DirectCode organization, and add anyone who wants to help assist in maintaining it (including me) can be added as collaborators.

**Comment by kaendfinger** [comment]
Also, thanks @luizmineo for this, I will, with the rest of the people who want to, keep it alive :)

**Comment by kaendfinger** [comment]
As long as others agree :)

**Comment by cgarciae** [comment]
@kaendfinger Will moving Redstone to DirectCode will somehow make it private?

**Comment by kaendfinger** [comment]
@cgarciae No, of course not. DirectCode is simply just a group of people who code cool stuff. I'll add anyone who is willing to become a maintainer to it, with full permissions.

**Comment by kaendfinger** [comment]
https://github.com/DirectMyFile/redstone.dart

**Comment by kaendfinger** [comment]
@cgarciae Do you have access to the repo?

**Comment by cgarciae** [comment]
@kaendfinger Yes. I am fine with it. If we take this direction, please add me to DirectCode.

**Comment by kaendfinger** [comment]
@cgarciae Added. Do you have access to move the repository, or are we going to fork it?

**Comment by cgarciae** [comment]
@kaendfinger To move it we have to wait for Luiz to do this. He just posted the message this morning, maybe he will want to hear from the rest of the community before doing this. Lets see what he says :)

**Comment by kaendfinger** [comment]
Ok. :) Sounds great. Thanks!

**Comment by kaendfinger** [comment]
@luizmineo @cgarciae

A couple things, if my proposal is taken:

- @austincummings has offered to take over the sub-packages like redstone_websocket, and these would be moved to DirectCode as well.
- What will happen with the domain? I will pay for it, if it is transferred to me.
- We will have a clear roadmap, and everything will be driven by the community.
- I would need to be added as an uploader to all the redstone packages, and then I will add all the maintainers.
- We will need to have @luizmineo comment as to what level he wants to be associated with the project. I propose that we keep his name and a link to his profile, and make a note that he was the original creator and maintainer. He can decide as to what happens though.

**Comment by kaendfinger** [comment]
@luizmineo @cgarciae Along with my proposal, we could also move https://github.com/luizmineo/connection_pool

**Comment by cgarciae** [comment]
@kaendfinger Thanks for your enthusiasm!

I think @luizmineo will actually like all this, maybe he was expecting it. I don't know how other open-source projects evolve, but there has to be a moment when the community takes over somehow.

I also propose this as a development model, the intention is to make it clear for the community what is going to be implemented next, what is missing, and what is broken, so people can contribute more easily and focused on a general goal
*  Release based
*  Define a set of features for each release
*  Implement a **broken feature** first, might be a new class with empty methods, new empty methods on an existing class, or an empty branch of code on an existing method. Example
```dart
class SomeClass
{
    C newMethod(A a, B b)
    {
        throw new UnimplmentedError ();
    }
    
    D existingMethod (F f, H h, X newParam)
    {
        //Existing code
        ...
        //New Code
        if (someCondition)
        {
            throw new UnimplmentedError ();
        }
        ...
    }
}
```
*  Define **empty test** with no actual code. Example
```dart
group ("New Feature X", ()
{
    test ("some test", ()
    {
        throw new UnimplementedError ();
    });
});
```
*  Mark progress based on **passed tests** and report somewhere the status of the tests and tell the community what is missing.

Granted we are not paid to do this, but the organization to achieve this is not much: discussions on issues for new features or the contents of the next release, implement the broken tests and the new broken features. After that it might be a slow process making all the tests pass. But the benefit is that is **organized**, **measurable** and **clear**, so people can contribute more easily.

**Comment by kaendfinger** [comment]
@cgarciae I like it.

**Comment by luizmineo** [comment]
Guys, I'm really glad to see this movement to keep the project alive. It's truly amazing!

@kaendfinger I'll add you as a collaborator to each Redstone package. About the domain, I can keep paying for it, or I can transfer it if the community prefer this way. About the association level, I'm ok with your propose.
@cgarciae I'll write a topic about the internal code organization, and I can also try to answer any doubts you may have.

I'm really excited to see this project being community driven!

**Comment by kaendfinger** [comment]
@luizmineo Awesome! :) Thanks

Do you want me to fork it to DirectCode or would you prefer a move? A move would be easier (keep issues, wiki, and all) but I could fork if you prefer.

**Comment by kaendfinger** [comment]
@luizmineo Another option is to keep it on here. But I picked up from your README you didn't intend that.

**Comment by luizmineo** [comment]
@kaendfinger Yes, transferring it is the best option. I can transfer it to DirectCode, or maybe you can create a Redstone.dart organization. What do you guys prefer?

**Comment by austincummings** [comment]
I think it'd be best for there to be a Redstone. dart organization. Just my
opinion though.

**Comment by kaendfinger** [comment]
@luizmineo An organization is what it will be :)

**Comment by kaendfinger** [comment]
@luizmineo the organization is 'redstone-dart' you can transfer every redstone package there, oh and also, do you want to transfer connection_pool?

**Comment by luizmineo** [comment]
Awesome. Let's transfer all the repositories.

**Comment by cgarciae** [comment]
@luizmineo Please do! Something like a post in the Redstone blog on how certain key feature are implemented. I've read the the server implementation of `v0.5` and `v0.6` but I have no idea where certain critical things happen
*  Where is the actual route function/method called?
*  Where are the plugins/interceptors/error handlers called?
*  Where do you decide which function/route responds?
*  How is DI done?

**Comment by cgarciae** [comment]
@kaendfinger, @austincummings, @luizmineo
Redstone.dart organization sounds nice! Please add me :)

**Comment by luizmineo** [comment]
done!

**Comment by kubeliv** [comment]
I can't wait to see the future of redstone! I'm a member of DirectCode, by the way.

**Comment by adam-singer** [comment]
I think the best bet is to make an organization for redstone and add the appropriate people who can help maintain it.

**Comment by adam-singer** [comment]
nevermind, looks like that has already been done :100:

**Comment by azenla** [comment]
With this, I believe this can be closed! Thanks so much @luizmineo for making this! I am happy to be on board.

**Comment by Scorpiion** [comment]
Hi, things are moving forward quickly here, sorry to hear that you will not have so much time any longer to put on open source Dart projects @luizmineo. I hope what other things you have planned will go your way. Thanks for all the time and effort you have put into this project. :)

At the same time I must say it's fun to see the enthusiasm from you guys @kaendfinger and @cgarciae! I think Redstone will continue to grow with this new project structure. I don't have too much time right now to code on Redstone, but I do have some experience with Dart frameworks overall and could help out if there is something specific, just send me a ping.

As some might know I work on DartVoid, and we have not publicly announced this yet, but we plan to offer free hosting for open source Dart projects such as Redstone. So if you guys want, I would be happy to help out with that and get Redstone's own site built with Redstone, dogfooding is always good for software projects in my experience. Right now not everyone have access to DartVoid, but it will change between now and the Dart Summit, we are rolling out a lot of new stuff under the covers right now.

**Comment by azenla** [comment]
@Scorpiion Great idea! If we could do that, it would be great. I can add you to the organization as well :)

**Comment by Scorpiion** [comment]
Sounds good, would be happy to join the org! :)

**Comment by Pacane** [comment]
Me too! :)

**Comment by dzenanr** [comment]
I would like to join the project. I would be able to put few hours of work every week this summer. However, starting in September of this year, I will have more free time.﻿

**Comment by azenla** [comment]
@dzenanr @Pacane Sure! You guys can PR for the time being. @redstone-dart/owners will need to decide how we determine who goes in what team.

**Comment by Scorpiion** [comment]
Not sure how this process should work exactly, but I can vouch for @dzenanr for what it's worth. He has done a lot of good things with/for Dart and is the author of the book [Learning Dart](https://www.packtpub.com/web-development/learning-dart).

**Comment by dzenanr** [comment]
Thank you Robert @Scorpiion.

**Comment by azenla** [comment]
Ok, sure thing, adding now.

**Comment by Scorpiion** [comment]
Sounds good :+1:

**Comment by azenla** [comment]
@luizmineo I am not an uploader for redstone packages.

```
pub uploader add kaendfinger@gmail.com --package=redstone
```

If you can run that for each of the packages, I can upload new versions :)

**Comment by luizmineo** [comment]
done!

2015-04-14 1:03 GMT-03:00 Kenneth Endfinger notifications@github.com:

**Comment by azenla** [comment]
Thanks! :)
